environment:
  AZURE_SMB_KEY:
    secure: if71+kDyW4wl7Xbfgzi5G0Faau1OcfdfT/KU9LK+9Cmjv/DINmssTw/bfsqvDfie4RiDUsy/zMCOiSxQZ9IkiHVgx9lrkfZ1/ysDn50qwvklCKJhTjhS+UQQ8cJPrZ9q

init:
- appveyor version
- ps: systeminfo

test_script:
#- ps: Disable-NetFirewallRule -DisplayGroup 'File and Printer Sharing' -Direction Outbound
#- ps: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
- 'net use J: \\appveyordevtestdeleteme.file.core.windows.net\test101 /u:AZURE\appveyordevtestdeleteme %AZURE_SMB_KEY%'

build: off
